namespace Doozy.Runtime.Reactor.Easings;

public enum Ease
{
	Linear = 0,
	Easy = 1,
	InEasy = 2,
	OutEasy = 3,
	InOutEasy = 4,
	InSine = 5,
	OutSine = 6,
	InOutSine = 7,
	InQuad = 8,
	OutQuad = 9,
	InOutQuad = 10,
	InCubic = 11,
	OutCubic = 12,
	InOutCubic = 13,
	InQuart = 14,
	OutQuart = 15,
	InOutQuart = 16,
	InQuint = 17,
	OutQuint = 18,
	InOutQuint = 19,
	InExpo = 20,
	OutExpo = 21,
	InOutExpo = 22,
	InCirc = 23,
	OutCirc = 24,
	InOutCirc = 25,
	InBack = 26,
	OutBack = 27,
	InOutBack = 28,
	InElastic = 29,
	OutElastic = 30,
	InOutElastic = 31,
	InBounce = 32,
	OutBounce = 33,
	InOutBounce = 34,
	Spring = 35
}
