using System;
using System.Xml.Serialization;

namespace NPOI.OpenXmlFormats.Wordprocessing;

[Serializable]
[XmlType(Namespace = "http://schemas.openxmlformats.org/wordprocessingml/2006/main")]
public enum ST_NumberFormat
{
	[XmlEnum("decimal")]
	@decimal = 0,
	upperRoman = 1,
	lowerRoman = 2,
	upperLetter = 3,
	lowerLetter = 4,
	ordinal = 5,
	cardinalText = 6,
	ordinalText = 7,
	hex = 8,
	chicago = 9,
	ideographDigital = 10,
	japaneseCounting = 11,
	aiueo = 12,
	iroha = 13,
	decimalFullWidth = 14,
	decimalHalfWidth = 15,
	japaneseLegal = 16,
	japaneseDigitalTenThousand = 17,
	decimalEnclosedCircle = 18,
	decimalFullWidth2 = 19,
	aiueoFullWidth = 20,
	irohaFullWidth = 21,
	decimalZero = 22,
	bullet = 23,
	ganada = 24,
	chosung = 25,
	decimalEnclosedFullstop = 26,
	decimalEnclosedParen = 27,
	decimalEnclosedCircleChinese = 28,
	ideographEnclosedCircle = 29,
	ideographTraditional = 30,
	ideographZodiac = 31,
	ideographZodiacTraditional = 32,
	taiwaneseCounting = 33,
	ideographLegalTraditional = 34,
	taiwaneseCountingThousand = 35,
	taiwaneseDigital = 36,
	chineseCounting = 37,
	chineseLegalSimplified = 38,
	chineseCountingThousand = 39,
	koreanDigital = 40,
	koreanCounting = 41,
	koreanLegal = 42,
	koreanDigital2 = 43,
	vietnameseCounting = 44,
	russianLower = 45,
	russianUpper = 46,
	none = 47,
	numberInDash = 48,
	hebrew1 = 49,
	hebrew2 = 50,
	arabicAlpha = 51,
	arabicAbjad = 52,
	hindiVowels = 53,
	hindiConsonants = 54,
	hindiNumbers = 55,
	hindiCounting = 56,
	thaiLetters = 57,
	thaiNumbers = 58,
	thaiCounting = 59
}
