<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>DoozyRuntime</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoStandardLib>True</NoStandardLib>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>False</AppendRuntimeIdentifierToOutputPath>
    <DisableImplicitConfigurationDefines>True</DisableImplicitConfigurationDefines>
    <DisableImplicitFrameworkDefines>True</DisableImplicitFrameworkDefines>
    <DisableImplicitFrameworkReferences>True</DisableImplicitFrameworkReferences>
    <DisableTransitiveProjectReferences>True</DisableTransitiveProjectReferences>
    <DisableImplicitNamespaceImports>True</DisableImplicitNamespaceImports>
    <EnsureRuntimePackageDependencies>False</EnsureRuntimePackageDependencies>
    <AddAdditionalExplicitAssemblyReferences>False</AddAdditionalExplicitAssemblyReferences>
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <ProjectReference Include="../UnityEngine.CoreModule/UnityEngine.CoreModule.csproj" />
    <ProjectReference Include="../mscorlib/mscorlib.csproj" />
    <ProjectReference Include="../Unity.InputSystem/Unity.InputSystem.csproj" />
    <ProjectReference Include="../UnityEngine.UI/UnityEngine.UI.csproj" />
    <ProjectReference Include="../UnityEngine.UIModule/UnityEngine.UIModule.csproj" />
    <ProjectReference Include="../System.Core/System.Core.csproj" />
    <ProjectReference Include="../UnityEngine.AudioModule/UnityEngine.AudioModule.csproj" />
    <ProjectReference Include="../Unity.TextMeshPro/Unity.TextMeshPro.csproj" />
    <ProjectReference Include="../UnityEngine.UIElementsModule/UnityEngine.UIElementsModule.csproj" />
    <ProjectReference Include="../UnityEngine.IMGUIModule/UnityEngine.IMGUIModule.csproj" />
    <ProjectReference Include="../UnityEngine.TextRenderingModule/UnityEngine.TextRenderingModule.csproj" />
    <ProjectReference Include="../System/System.csproj" />
    <ProjectReference Include="../UnityEngine.SpriteMaskModule/UnityEngine.SpriteMaskModule.csproj" />
    <ProjectReference Include="../UnityEngine.AnimationModule/UnityEngine.AnimationModule.csproj" />
    <ProjectReference Include="../UnityEngine.InputLegacyModule/UnityEngine.InputLegacyModule.csproj" />
    <ProjectReference Include="../UnityEngine.ImageConversionModule/UnityEngine.ImageConversionModule.csproj" />
    <ProjectReference Include="../UnityEngine.JSONSerializeModule/UnityEngine.JSONSerializeModule.csproj" />
  </ItemGroup>
</Project>