<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Unity.Services.Core.Registration</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoStandardLib>True</NoStandardLib>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>False</AppendRuntimeIdentifierToOutputPath>
    <DisableImplicitConfigurationDefines>True</DisableImplicitConfigurationDefines>
    <DisableImplicitFrameworkDefines>True</DisableImplicitFrameworkDefines>
    <DisableImplicitFrameworkReferences>True</DisableImplicitFrameworkReferences>
    <DisableTransitiveProjectReferences>True</DisableTransitiveProjectReferences>
    <DisableImplicitNamespaceImports>True</DisableImplicitNamespaceImports>
    <EnsureRuntimePackageDependencies>False</EnsureRuntimePackageDependencies>
    <AddAdditionalExplicitAssemblyReferences>False</AddAdditionalExplicitAssemblyReferences>
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <ProjectReference Include="../Unity.Services.Core.Scheduler/Unity.Services.Core.Scheduler.csproj" />
    <ProjectReference Include="../Unity.Services.Core.Device/Unity.Services.Core.Device.csproj" />
    <ProjectReference Include="../Unity.Services.Core.Configuration/Unity.Services.Core.Configuration.csproj" />
    <ProjectReference Include="../Unity.Services.Core.Environments.Internal/Unity.Services.Core.Environments.Internal.csproj" />
    <ProjectReference Include="../Unity.Services.Core.Internal/Unity.Services.Core.Internal.csproj" />
    <ProjectReference Include="../Unity.Services.Core.Threading/Unity.Services.Core.Threading.csproj" />
    <ProjectReference Include="../mscorlib/mscorlib.csproj" />
    <ProjectReference Include="../Unity.Services.Core/Unity.Services.Core.csproj" />
    <ProjectReference Include="../System/System.csproj" />
    <ProjectReference Include="../Newtonsoft.Json/Newtonsoft.Json.csproj" />
    <ProjectReference Include="../UnityEngine.CoreModule/UnityEngine.CoreModule.csproj" />
    <ProjectReference Include="../Unity.Services.Core.Telemetry/Unity.Services.Core.Telemetry.csproj" />
  </ItemGroup>
</Project>