namespace NPOI.XSSF.UserModel;

public enum ListAutoNumber
{
	ALPHA_LC_PARENT_BOTH = 0,
	ALPHA_UC_PARENT_BOTH = 1,
	ALPHA_LC_PARENT_R = 2,
	ALPHA_UC_PARENT_R = 3,
	ALPHA_LC_PERIOD = 4,
	ALPHA_UC_PERIOD = 5,
	ARABIC_PARENT_BOTH = 6,
	ARABIC_PARENT_R = 7,
	ARABIC_PERIOD = 8,
	ARABIC_PLAIN = 9,
	ROMAN_LC_PARENT_BOTH = 10,
	ROMAN_UC_PARENT_BOTH = 11,
	ROMAN_LC_PARENT_R = 12,
	ROMAN_UC_PARENT_R = 13,
	ROMAN_LC_PERIOD = 14,
	ROMAN_UC_PERIOD = 15,
	CIRCLE_NUM_DB_PLAIN = 16,
	CIRCLE_NUM_WD_BLACK_PLAIN = 17,
	CIRCLE_NUM_WD_WHITE_PLAIN = 18
}
