<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>netstandard</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoStandardLib>True</NoStandardLib>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>False</AppendRuntimeIdentifierToOutputPath>
    <DisableImplicitConfigurationDefines>True</DisableImplicitConfigurationDefines>
    <DisableImplicitFrameworkDefines>True</DisableImplicitFrameworkDefines>
    <DisableImplicitFrameworkReferences>True</DisableImplicitFrameworkReferences>
    <DisableTransitiveProjectReferences>True</DisableTransitiveProjectReferences>
    <DisableImplicitNamespaceImports>True</DisableImplicitNamespaceImports>
    <EnsureRuntimePackageDependencies>False</EnsureRuntimePackageDependencies>
    <AddAdditionalExplicitAssemblyReferences>False</AddAdditionalExplicitAssemblyReferences>
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <ProjectReference Include="../mscorlib/mscorlib.csproj" />
    <ProjectReference Include="../System.Core/System.Core.csproj" />
    <ProjectReference Include="../System/System.csproj" />
    <ProjectReference Include="../System.Data/System.Data.csproj" />
    <ProjectReference Include="../System.Data.DataSetExtensions/System.Data.DataSetExtensions.csproj" />
    <ProjectReference Include="../System.Drawing/System.Drawing.csproj" />
    <ProjectReference Include="../System.IO.Compression/System.IO.Compression.csproj" />
    <ProjectReference Include="../System.IO.Compression.FileSystem/System.IO.Compression.FileSystem.csproj" />
    <ProjectReference Include="../System.ComponentModel.Composition/System.ComponentModel.Composition.csproj" />
    <ProjectReference Include="../System.Net.Http/System.Net.Http.csproj" />
    <ProjectReference Include="../System.Numerics/System.Numerics.csproj" />
    <ProjectReference Include="../System.Runtime.Serialization/System.Runtime.Serialization.csproj" />
    <ProjectReference Include="../System.Transactions/System.Transactions.csproj" />
    <ProjectReference Include="../System.Xml/System.Xml.csproj" />
    <ProjectReference Include="../System.Xml.Linq/System.Xml.Linq.csproj" />
  </ItemGroup>
</Project>