using System;
using System.Xml.Serialization;

namespace NPOI.OpenXmlFormats.Vml.Spreadsheet;

[Serializable]
[XmlType(Namespace = "urn:schemas-microsoft-com:office:excel", IncludeInSchema = false)]
public enum ItemsChoiceType
{
	Accel = 0,
	Accel2 = 1,
	Anchor = 2,
	AutoFill = 3,
	AutoLine = 4,
	AutoPict = 5,
	AutoScale = 6,
	CF = 7,
	Camera = 8,
	Cancel = 9,
	Checked = 10,
	ColHidden = 11,
	Colored = 12,
	Column = 13,
	DDE = 14,
	Default = 15,
	DefaultSize = 16,
	Disabled = 17,
	Dismiss = 18,
	DropLines = 19,
	DropStyle = 20,
	Dx = 21,
	FirstButton = 22,
	FmlaGroup = 23,
	FmlaLink = 24,
	FmlaMacro = 25,
	FmlaPict = 26,
	FmlaRange = 27,
	FmlaTxbx = 28,
	Help = 29,
	Horiz = 30,
	Inc = 31,
	JustLastX = 32,
	LCT = 33,
	ListItem = 34,
	LockText = 35,
	Locked = 36,
	MapOCX = 37,
	Max = 38,
	Min = 39,
	MoveWithCells = 40,
	MultiLine = 41,
	MultiSel = 42,
	NoThreeD = 43,
	NoThreeD2 = 44,
	Page = 45,
	PrintObject = 46,
	RecalcAlways = 47,
	Row = 48,
	RowHidden = 49,
	ScriptExtended = 50,
	ScriptLanguage = 51,
	ScriptLocation = 52,
	ScriptText = 53,
	SecretEdit = 54,
	Sel = 55,
	SelType = 56,
	SizeWithCells = 57,
	TextHAlign = 58,
	TextVAlign = 59,
	UIObj = 60,
	VScroll = 61,
	VTEdit = 62,
	Val = 63,
	ValidIds = 64,
	Visible = 65,
	WidthMin = 66
}
