public enum TriggerEventType
{
	PLAY_ANIM = 0,
	INTERACT_ITEM = 1,
	SPAWN_ENEMIES = 2,
	WAKEUP_ENEMIES = 3,
	KNOCK_KNOCK = 4,
	ENVIRONMENT_SEQUENCE = 5,
	CHASE_TARGET = 6,
	MONOLOGUE_LOCAL = 7,
	DROP_ITEM = 8,
	TUTORIAL_MELEE = 9,
	TUTORIAL_RANGE = 10,
	TUTORIAL_MOVE = 11,
	TUTORIAL_SPRINT = 12,
	TUTORIAL_DASH = 13,
	DISABLE_DEAF = 14,
	ACTIVATE_OBJECT = 15
}
