<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>UnityEngine</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoStandardLib>True</NoStandardLib>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>False</AppendRuntimeIdentifierToOutputPath>
    <DisableImplicitConfigurationDefines>True</DisableImplicitConfigurationDefines>
    <DisableImplicitFrameworkDefines>True</DisableImplicitFrameworkDefines>
    <DisableImplicitFrameworkReferences>True</DisableImplicitFrameworkReferences>
    <DisableTransitiveProjectReferences>True</DisableTransitiveProjectReferences>
    <DisableImplicitNamespaceImports>True</DisableImplicitNamespaceImports>
    <EnsureRuntimePackageDependencies>False</EnsureRuntimePackageDependencies>
    <AddAdditionalExplicitAssemblyReferences>False</AddAdditionalExplicitAssemblyReferences>
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <ProjectReference Include="../netstandard/netstandard.csproj" />
    <ProjectReference Include="../UnityEngine.CoreModule/UnityEngine.CoreModule.csproj" />
    <ProjectReference Include="../UnityEngine.DSPGraphModule/UnityEngine.DSPGraphModule.csproj" />
    <ProjectReference Include="../UnityEngine.AudioModule/UnityEngine.AudioModule.csproj" />
    <ProjectReference Include="../UnityEngine.UnityCurlModule/UnityEngine.UnityCurlModule.csproj" />
    <ProjectReference Include="../UnityEngine.ContentLoadModule/UnityEngine.ContentLoadModule.csproj" />
    <ProjectReference Include="../UnityEngine.PropertiesModule/UnityEngine.PropertiesModule.csproj" />
    <ProjectReference Include="../UnityEngine.TLSModule/UnityEngine.TLSModule.csproj" />
    <ProjectReference Include="../UnityEngine.AndroidJNIModule/UnityEngine.AndroidJNIModule.csproj" />
    <ProjectReference Include="../UnityEngine.InputLegacyModule/UnityEngine.InputLegacyModule.csproj" />
    <ProjectReference Include="../UnityEngine.AccessibilityModule/UnityEngine.AccessibilityModule.csproj" />
    <ProjectReference Include="../UnityEngine.UIModule/UnityEngine.UIModule.csproj" />
    <ProjectReference Include="../UnityEngine.UnityConnectModule/UnityEngine.UnityConnectModule.csproj" />
    <ProjectReference Include="../UnityEngine.AIModule/UnityEngine.AIModule.csproj" />
    <ProjectReference Include="../UnityEngine.UnityAnalyticsModule/UnityEngine.UnityAnalyticsModule.csproj" />
    <ProjectReference Include="../UnityEngine.UnityAnalyticsCommonModule/UnityEngine.UnityAnalyticsCommonModule.csproj" />
    <ProjectReference Include="../UnityEngine.PerformanceReportingModule/UnityEngine.PerformanceReportingModule.csproj" />
    <ProjectReference Include="../UnityEngine.Physics2DModule/UnityEngine.Physics2DModule.csproj" />
    <ProjectReference Include="../UnityEngine.AnimationModule/UnityEngine.AnimationModule.csproj" />
    <ProjectReference Include="../UnityEngine.PhysicsModule/UnityEngine.PhysicsModule.csproj" />
    <ProjectReference Include="../UnityEngine.AssetBundleModule/UnityEngine.AssetBundleModule.csproj" />
    <ProjectReference Include="../UnityEngine.SharedInternalsModule/UnityEngine.SharedInternalsModule.csproj" />
    <ProjectReference Include="../UnityEngine.TextRenderingModule/UnityEngine.TextRenderingModule.csproj" />
    <ProjectReference Include="../UnityEngine.ClothModule/UnityEngine.ClothModule.csproj" />
    <ProjectReference Include="../UnityEngine.ClusterInputModule/UnityEngine.ClusterInputModule.csproj" />
    <ProjectReference Include="../UnityEngine.ClusterRendererModule/UnityEngine.ClusterRendererModule.csproj" />
    <ProjectReference Include="../UnityEngine.CrashReportingModule/UnityEngine.CrashReportingModule.csproj" />
    <ProjectReference Include="../UnityEngine.TilemapModule/UnityEngine.TilemapModule.csproj" />
    <ProjectReference Include="../UnityEngine.TerrainModule/UnityEngine.TerrainModule.csproj" />
    <ProjectReference Include="../UnityEngine.IMGUIModule/UnityEngine.IMGUIModule.csproj" />
    <ProjectReference Include="../UnityEngine.VFXModule/UnityEngine.VFXModule.csproj" />
    <ProjectReference Include="../UnityEngine.VideoModule/UnityEngine.VideoModule.csproj" />
    <ProjectReference Include="../UnityEngine.VRModule/UnityEngine.VRModule.csproj" />
    <ProjectReference Include="../UnityEngine.GridModule/UnityEngine.GridModule.csproj" />
    <ProjectReference Include="../UnityEngine.ImageConversionModule/UnityEngine.ImageConversionModule.csproj" />
    <ProjectReference Include="../UnityEngine.SubsystemsModule/UnityEngine.SubsystemsModule.csproj" />
    <ProjectReference Include="../UnityEngine.JSONSerializeModule/UnityEngine.JSONSerializeModule.csproj" />
    <ProjectReference Include="../UnityEngine.LocalizationModule/UnityEngine.LocalizationModule.csproj" />
    <ProjectReference Include="../UnityEngine.UnityWebRequestModule/UnityEngine.UnityWebRequestModule.csproj" />
    <ProjectReference Include="../UnityEngine.UnityWebRequestAssetBundleModule/UnityEngine.UnityWebRequestAssetBundleModule.csproj" />
    <ProjectReference Include="../UnityEngine.UnityWebRequestAudioModule/UnityEngine.UnityWebRequestAudioModule.csproj" />
    <ProjectReference Include="../UnityEngine.UnityWebRequestTextureModule/UnityEngine.UnityWebRequestTextureModule.csproj" />
    <ProjectReference Include="../UnityEngine.UnityWebRequestWWWModule/UnityEngine.UnityWebRequestWWWModule.csproj" />
    <ProjectReference Include="../UnityEngine.NVIDIAModule/UnityEngine.NVIDIAModule.csproj" />
    <ProjectReference Include="../UnityEngine.ParticleSystemModule/UnityEngine.ParticleSystemModule.csproj" />
    <ProjectReference Include="../UnityEngine.DirectorModule/UnityEngine.DirectorModule.csproj" />
    <ProjectReference Include="../UnityEngine.VirtualTexturingModule/UnityEngine.VirtualTexturingModule.csproj" />
    <ProjectReference Include="../UnityEngine.ScreenCaptureModule/UnityEngine.ScreenCaptureModule.csproj" />
    <ProjectReference Include="../UnityEngine.GameCenterModule/UnityEngine.GameCenterModule.csproj" />
    <ProjectReference Include="../UnityEngine.SpriteMaskModule/UnityEngine.SpriteMaskModule.csproj" />
    <ProjectReference Include="../UnityEngine.StreamingModule/UnityEngine.StreamingModule.csproj" />
    <ProjectReference Include="../UnityEngine.TerrainPhysicsModule/UnityEngine.TerrainPhysicsModule.csproj" />
    <ProjectReference Include="../UnityEngine.TextCoreFontEngineModule/UnityEngine.TextCoreFontEngineModule.csproj" />
    <ProjectReference Include="../UnityEngine.TextCoreTextEngineModule/UnityEngine.TextCoreTextEngineModule.csproj" />
    <ProjectReference Include="../UnityEngine.SpriteShapeModule/UnityEngine.SpriteShapeModule.csproj" />
    <ProjectReference Include="../UnityEngine.UIElementsModule/UnityEngine.UIElementsModule.csproj" />
    <ProjectReference Include="../UnityEngine.VehiclesModule/UnityEngine.VehiclesModule.csproj" />
    <ProjectReference Include="../UnityEngine.WindModule/UnityEngine.WindModule.csproj" />
    <ProjectReference Include="../UnityEngine.XRModule/UnityEngine.XRModule.csproj" />
    <ProjectReference Include="../UnityEngine.ARModule/UnityEngine.ARModule.csproj" />
    <ProjectReference Include="../UnityEngine.InputModule/UnityEngine.InputModule.csproj" />
  </ItemGroup>
</Project>