<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>UnityEngine.ClusterRendererModule</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoStandardLib>True</NoStandardLib>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>False</AppendRuntimeIdentifierToOutputPath>
    <DisableImplicitConfigurationDefines>True</DisableImplicitConfigurationDefines>
    <DisableImplicitFrameworkDefines>True</DisableImplicitFrameworkDefines>
    <DisableImplicitFrameworkReferences>True</DisableImplicitFrameworkReferences>
    <DisableTransitiveProjectReferences>True</DisableTransitiveProjectReferences>
    <DisableImplicitNamespaceImports>True</DisableImplicitNamespaceImports>
    <EnsureRuntimePackageDependencies>False</EnsureRuntimePackageDependencies>
    <AddAdditionalExplicitAssemblyReferences>False</AddAdditionalExplicitAssemblyReferences>
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <ProjectReference Include="../UnityEngine.CoreModule/UnityEngine.CoreModule.csproj" />
    <ProjectReference Include="../netstandard/netstandard.csproj" />
    <ProjectReference Include="../UnityEngine.SharedInternalsModule/UnityEngine.SharedInternalsModule.csproj" />
  </ItemGroup>
</Project>