using System;
using System.Xml.Serialization;

namespace NPOI.OpenXmlFormats.Dml.Diagram;

[Serializable]
[XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/diagram")]
public enum ST_ParameterId
{
	horzAlign = 0,
	vertAlign = 1,
	chDir = 2,
	chAlign = 3,
	secChAlign = 4,
	linDir = 5,
	secLinDir = 6,
	stElem = 7,
	bendPt = 8,
	connRout = 9,
	begSty = 10,
	endSty = 11,
	dim = 12,
	rotPath = 13,
	ctrShpMap = 14,
	nodeHorzAlign = 15,
	nodeVertAlign = 16,
	fallback = 17,
	txDir = 18,
	pyraAcctPos = 19,
	pyraAcctTxMar = 20,
	txBlDir = 21,
	txAnchorHorz = 22,
	txAnchorVert = 23,
	txAnchorHorzCh = 24,
	txAnchorVertCh = 25,
	parTxLTRAlign = 26,
	parTxRTLAlign = 27,
	shpTxLTRAlignCh = 28,
	shpTxRTLAlignCh = 29,
	autoTxRot = 30,
	grDir = 31,
	flowDir = 32,
	contDir = 33,
	bkpt = 34,
	off = 35,
	hierAlign = 36,
	bkPtFixedVal = 37,
	stBulletLvl = 38,
	stAng = 39,
	spanAng = 40,
	ar = 41,
	lnSpPar = 42,
	lnSpAfParP = 43,
	lnSpCh = 44,
	lnSpAfChP = 45,
	rtShortDist = 46,
	alignTx = 47,
	pyraLvlNode = 48,
	pyraAcctBkgdNode = 49,
	pyraAcctTxNode = 50,
	srcNode = 51,
	dstNode = 52,
	begPts = 53,
	endPts = 54
}
